"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:52:32.738034+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, max as max_, broadcast
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os
from datetime import datetime

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(datetime.now().isoformat()))
                       .withColumn("source_file", lit("transactions.csv"))
                        .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                      .option("basePath", bronze_path)
                      .load(f"{bronze_path}/{run_date}"))
    
    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                       .withColumn("transaction_date", col("transaction_date").cast(DateType()))
                       .withColumn("transaction_id", col("transaction_id").cast(StringType()))
                       .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    
    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_df = (transactions_df.withColumn("rank", max_("ingestion_timestamp").over(window.partitionBy("transaction_id")))
                      .filter(col("rank") == col("ingestion_timestamp"))
                      .drop("rank"))
    
    # Read merchants data and cache it
    merchants_df = (spark.read.option("header", "true")
                   .csv(merchants_path)
                   .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    merchants_df = merchants_df.cache()
    
    # Enrich: join transactions with merchants on merchant_id
    enriched_df = (transactions_df.join(broadcast(merchants_df), "merchant_id", "left")
                  .withColumn("quality_flag", 
                               col("merchant_id").isNotNull().when(True, "CLEAN").otherwise("UNMATCHED")))
    
    # Write as Parquet partitioned by date
    enriched_df.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech-raw/transactions.csv"
    bronze_path = "s3://sigma-datatech-bronze/transactions"
    merchants_path = "s3://sigma-datatech-bronze/merchants"
    output_path = "s3://sigma-datatech-silver/transactions"
    run_date = datetime.now().strftime("%Y-%m-%d")
    run_id = datetime.now().strftime("%Y%m%d%H%M%S")
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, f"{bronze_path}/{run_date}", run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, f"{bronze_path}/{run_date}", merchants_path, f"{output_path}/{run_date}", run_date)
    
    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "input_path": input_path, "output_path": output_path}
    with open(f"s3://sigma-datatech-metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, mode, coalesce, to_date, lit
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Build the three gold tables
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)

    # Write run metadata summary to a JSON file
    run_metadata = {
        "run_date": run_date,
        "status": "COMPLETED"
    }
    spark.range(1).write.json(f"{gold_output_dir}/run_metadata", mode="overwrite")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)

    # Calculate metrics
    merchant_performance_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write to Gold layer
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)

    # Calculate customer LTV metrics
    customer_ltv_df = silver_df.filter(col("status") == "COMPLETED") \
       .groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            coalesce(mode("payment_method").over(Window.partitionBy("customer_id")), lit(None)).alias("preferred_payment_method")
        )

    # Write to Gold layer
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)

    # Calculate daily summary metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(lit(0))).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(distinct("customer_id")).alias("unique_customers"),
            count(distinct("merchant_id")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write to Gold layer
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

if __name__ == "__main__":
    spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
    silver_path = "s3://your-bucket/silver/"
    gold_output_dir = "s3://your-bucket/gold/"
    run_date = "2026-05-27"
    run_gold(spark, silver_path, gold_output_dir, run_date)
