"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:51:17.293933+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_date, lit, broadcast, when
from pyspark.sql.types import StringType, DoubleType, DateType
import datetime

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read CSV with all columns as strings
    bronze_df = spark.read.csv(input_path, header=True, inferSchema=True)
    
    # Add ingestion_timestamp, source_file, pipeline_run_id columns
    bronze_df = bronze_df.withColumn("_ingestion_timestamp", lit(datetime.datetime.utcnow()))
    bronze_df = bronze_df.withColumn("_source_file", lit(input_path))
    bronze_df = bronze_df.withColumn("_batch_id", lit(run_id))
    
    # Write Parquet partitioned by date
    bronze_df.write.mode('overwrite').partitionBy('txn_date').parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    bronze_df = spark.read.parquet(bronze_path).where(col("txn_date") == run_date)
    
    # Cast columns to correct types
    bronze_df = bronze_df.withColumn("amount", col("amount").cast(DoubleType()))
    bronze_df = bronze_df.withColumn("txn_date", col("txn_date").cast(DateType()))
    bronze_df = bronze_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    
    # Filter NULL transaction_id and negative amounts
    bronze_df = bronze_df.filter(col("transaction_id").isNotNull() & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    bronze_df = bronze_df.sortWithinPartitions("transaction_id", "_ingestion_timestamp").dropDuplicates(["transaction_id"])
    
    # Read merchants data and cache it
    merchants_df = spark.read.parquet(merchants_path)
    merchants_df = merchants_df.hint("broadcast")
    spark.catalog.cacheTable("merchants")
    
    # Join with merchants
    silver_df = bronze_df.join(broadcast(merchants_df), on="merchant_id", how="left")
    
    # Add quality_flag column (CLEAN or UNMATCHED)
    silver_df = silver_df.withColumn("quality_flag", 
                                     when(col("transaction_id").isNotNull() & col("customer_id").isNotNull() & 
                                          col("amount").isNotNull() & col("txn_date").isNotNull() & col("status").isNotNull(), "CLEAN")
                                     .otherwise("UNMATCHED"))
    
    # Write Parquet partitioned by date
    silver_df.write.mode('overwrite').partitionBy('txn_date').parquet(output_path)

def main():
    spark = (SparkSession.builder
             .appName("DataQualityScorecardPipeline")
             .getOrCreate())
    
    input_path = "s3://path/to/bronze/input"
    bronze_output_path = "s3://path/to/bronze/output"
    merchants_path = "s3://path/to/merchants/data"
    silver_output_path = "s3://path/to/silver/output"
    run_date = datetime.date.today().isoformat()
    run_id = "run_id_12345"
    
    ingest_bronze(spark, input_path, bronze_output_path, run_date, run_id)
    transform_silver(spark, bronze_output_path, merchants_path, silver_output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, count, countDistinct, isnan, when, lit
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver transactions data
    silver_df = spark.read.format("delta").load(silver_path)
    silver_df = silver_df.filter(col("txn_date") == run_date)

    # Calculate merchant performance metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "txn_date") \
        .agg(
            count("amount").alias("txn_count"),
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count(when(col("status") == "FAILED", col("transaction_id"))).alias("failed_txn_count")
        ).withColumn("failure_rate_pct", (col("failed_txn_count") / col("txn_count")) * 100)

    # Write merchant performance to output path
    merchant_performance_df.write.mode("overwrite").partitionBy("txn_date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver transactions data
    silver_df = spark.read.format("delta").load(silver_path)

    # Calculate customer LTV metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount"))).alias("total_spent"),
            count("*").alias("total_txns"),
            max("txn_date").alias("first_txn_date"),
            min("txn_date").alias("last_txn_date")
        )

    # Determine preferred payment method (mode)
    payment_method_df = silver_df.groupBy("customer_id", "payment_method") \
       .agg(count("*").alias("payment_count")) \
        .groupBy("customer_id") \
       .agg(when(col("payment_count") == 
                  max("payment_count").over(window.partitionBy("customer_id")), col("payment_method")).alias("preferred_payment_method"))

    # Join LTV and preferred payment method
    customer_ltv_df = customer_ltv_df.join(payment_method_df, "customer_id", "left_outer")

    # Write customer LTV to output path
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver transactions data
    silver_df = spark.read.format("delta").load(silver_path)
    silver_df = silver_df.filter(col("txn_date") == run_date)

    # Calculate daily summary metrics
    daily_summary_df = silver_df.groupBy("txn_date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount"))).alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            count(when(col("status") == "FAILED", col("transaction_id"))).alias("failed_txn_count")
        ).withColumn("failure_rate_pct", (col("failed_txn_count") / col("total_txns")) * 100)

    # Write daily summary to output path
    daily_summary_df.write.mode("overwrite").partitionBy("txn_date").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths for each Gold layer component
    merchant_performance_output_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_output_path = f"{gold_output_dir}/daily_summary"

    # Run each Gold layer component
    build_merchant_performance(spark, silver_path, merchant_performance_output_path, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_output_path)
    build_daily_summary(spark, silver_path, daily_summary_output_path, run_date)

    # Write run metadata to JSON
    run_metadata = {
        "run_date": run_date,
        "status": "SUCCESS",
        "error_message": ""
    }
    spark.sparkContext.parallelize([run_metadata]).write.mode("overwrite").json(f"{gold_output_dir}/run_metadata")

def data_quality_scorecard(spark, silver_path, output_path, run_date):
    # Read Silver transactions data
    silver_df = spark.read.format("delta").load(silver_path)
    silver_df = silver_df.filter(col("txn_date") == run_date)

    # Check if Silver table is missing or empty
    if silver_df.rdd.isEmpty():
        raise Exception("E001: Silver table is missing or empty")

    # Calculate null rate per column
    null_rate_cols = {col_name: (count(when(isnan(col(col_name)) | col(col_name).isNull(), col(col_name))) / count("*") for col_name in silver_df.columns}

    # Calculate duplicate rate
    duplicate_rate = (silver_df.count() - silver_df.distinct("transaction_id").count()) / silver_df.count()

    # Check schema match
    expected_columns = {"transaction_id", "customer_id", "amount", "txn_date", "status"}
    schema_match = 1 if expected_columns.issubset(set(silver_df.columns)) else 0

    # Calculate overall quality score
    overall_quality_score = 100 - (null_rate_cols["amount"] * 40 + duplicate_rate * 40 + (1 - schema_match) * 20)

    # Prepare data quality scorecard
    scorecard_df = spark.createDataFrame([(
        run_date,
        null_rate_cols["transaction_id"],
        null_rate_cols["customer_id"],
        null_rate_cols["amount"],
        null_rate_cols["txn_date"],
        null_rate_cols["status"],
        duplicate_rate,
        schema_match,
        overall_quality_score,
        "HALTED" if overall_quality_score < 60 else "SUCCESS"
    )], StructType([
        StructField("run_date", DateType(), True),
        StructField("null_rate_transaction_id", DoubleType(), True),
        StructField("null_rate_customer_id", DoubleType(), True),
        StructField("null_rate_amount", DoubleType(), True),
        StructField("null_rate_txn_date", DoubleType(), True),
        StructField("null_rate_status", DoubleType(), True),
        StructField("duplicate_rate", DoubleType(), True),
        StructField("schema_match", DoubleType(), True),
        StructField("overall_quality_score", DoubleType(), True),
        StructField("pipeline_status", StringType(), True)
    ]))

    # Write data quality scorecard to output path
    scorecard_df.write.mode("overwrite").parquet(output_path)

    # Log pipeline status
    run_metadata = {
        "run_date": run_date,
        "status": "HALTED" if overall_quality_score < 60 else "SUCCESS",
        "error_message": "" if overall_quality_score >= 60 else "Overall quality score below threshold"
    }
    spark.sparkContext.parallelize([run_metadata]).write.mode("overwrite").json(f"{output_path}/run_metadata")
