
"""
==============================================================================
TOOL: write_incident_report.py
==============================================================================
Purpose:
    Generates AI-driven incident postmortem reports.

Features:
    - Executive incident summaries
    - Root cause analysis
    - Business impact reporting
    - Recovery timeline synthesis
    - Agent performance analytics

Writes:
    - Markdown report (local: lab/agent_outputs/)
    - JSON report    (local: lab/agent_outputs/)

Storage:
    Primary   : Local filesystem  → lab/agent_outputs/
    Secondary : Azure Blob Storage (optional — skipped if not configured)

Used by:
    * Incident Report Agent
    * Supervisor Agent

==============================================================================
"""

import json
import os
from pathlib import Path

from datetime import datetime, timezone
from dotenv import load_dotenv


load_dotenv()

# ── Local output directory (always written) ──────────────────────────────────
_HERE          = Path(__file__).resolve().parent          # lab/tools/
_AGENT_OUTPUTS = _HERE.parent / "agent_outputs"           # lab/agent_outputs/
_AGENT_OUTPUTS.mkdir(parents=True, exist_ok=True)


# ── Main Report Writer ───────────────────────────────────────────────────────

def write_report(findings: dict) -> dict:

    ts = datetime.now(timezone.utc)

    md_filename   = f"incident_{ts.strftime('%Y%m%d_%H%M%S')}.md"
    json_filename = f"incident_{ts.strftime('%Y%m%d_%H%M%S')}.json"

    # ── Extract Findings ────────────────────────────────────────────────────

    forensics = findings.get("forensics", {})
    impact    = findings.get("impact", {})
    recovery  = findings.get("recovery", {})
    rollback  = findings.get("rollback", {})
    hardening = findings.get("hardening", {})

    # ── Markdown Report ─────────────────────────────────────────────────────

    md = f"""# Incident Report — {impact.get('gmv_gap_inr', 'Unknown')} GMV Loss

## Severity
{findings.get('severity', 'HIGH')}

## Detection Time
{findings.get('detection_ts', ts.isoformat())}

## Recovery Time
{ts.isoformat()}

## Summary

{findings.get(
    'summary',
    'Autonomous recovery workflow executed.'
)}

---

# Root Cause

{forensics.get(
    'root_cause_hypothesis',
    'See forensic analysis.'
)}

---

# Business Impact

| Metric | Value |
|---|---|
| Missing Records | {impact.get('records_missing', '?')} |
| GMV Gap | {impact.get('gmv_gap_inr', '?')} |
| Merchants Affected | {impact.get('merchants_affected', '?')} |
| SLA Breach | {impact.get('sla_breach', '?')} |

---

# Recovery Summary

{_build_fix_section(recovery, rollback)}

---

# Hardening Actions

{_build_hardening_section(hardening)}

---

# Agent Performance

{_build_agent_perf(findings)}

---

Generated by Sigma Intelligence Platform
{ts.isoformat()}
"""

    # ── 1. Write to local agent_outputs/ (always) ───────────────────────────

    local_md_path   = _AGENT_OUTPUTS / md_filename
    local_json_path = _AGENT_OUTPUTS / json_filename

    local_md_path.write_text(md, encoding="utf-8")
    local_json_path.write_text(
        json.dumps(findings, indent=2, default=str),
        encoding="utf-8"
    )

    print(f"  [write_incident_report] Local MD  : {local_md_path}")
    print(f"  [write_incident_report] Local JSON: {local_json_path}")

    result = {
        "status":          "WRITTEN",
        "markdown_report": str(local_md_path),
        "json_report":     str(local_json_path),
        "written_at":      ts.isoformat(),
    }

    # ── 2. Also upload to Azure Blob Storage (optional) ─────────────────────

    storage_connection_string = os.getenv("AZURE_STORAGE_CONNECTION_STRING")

    if storage_connection_string:
        try:
            from azure.storage.blob import BlobServiceClient
            blob_service_client = BlobServiceClient.from_connection_string(
                storage_connection_string
            )
            container_name = "reports"

            blob_service_client.get_blob_client(
                container=container_name, blob=md_filename
            ).upload_blob(md.encode("utf-8"), overwrite=True)

            blob_service_client.get_blob_client(
                container=container_name, blob=json_filename
            ).upload_blob(
                json.dumps(findings, indent=2, default=str).encode("utf-8"),
                overwrite=True
            )

            result["azure_blob_md"]   = f"{container_name}/{md_filename}"
            result["azure_blob_json"] = f"{container_name}/{json_filename}"
            print(
                f"  [write_incident_report] Azure Blob: "
                f"{container_name}/{md_filename}"
            )

        except Exception as azure_err:
            print(
                f"  [write_incident_report] Azure upload skipped: {azure_err}"
            )

    return result


# ── Helper Functions ─────────────────────────────────────────────────────────

def _build_fix_section(recovery: dict, rollback: dict) -> str:
    lines = []
    if rollback.get("status") == "SUCCESS":
        lines.append("- Deployment rollback completed successfully")
    if recovery.get("rows_loaded"):
        lines.append(
            f"- {recovery.get('rows_loaded')} records replayed into Snowflake"
        )
    if recovery.get("quarantined_count"):
        lines.append(
            f"- {recovery.get('quarantined_count')} records quarantined"
        )
    return "\n".join(lines)


def _build_hardening_section(hardening: dict) -> str:
    alarms = hardening.get("alarms_created", [])
    if not alarms:
        return "No hardening actions recorded."
    return "\n".join(
        f"- {a.get('alert_name', '?')}"
        for a in alarms
    )


def _build_agent_perf(findings: dict) -> str:
    perf = findings.get("agent_performance", [])
    if not perf:
        return "No performance metrics recorded."
    return "\n".join(
        f"- {p.get('agent')} ({p.get('duration_sec')} sec)"
        for p in perf
    )


# ── Local Test ───────────────────────────────────────────────────────────────

if __name__ == "__main__":

    sample_findings = {
        "severity": "HIGH",
        "summary": (
            "Azure Function deployment introduced schema drift."
        ),
        "forensics": {
            "root_cause_hypothesis": (
                "merchant_name renamed to merchant_nm"
            )
        },
        "impact": {
            "records_missing":    847,
            "gmv_gap_inr":        "₹4,72,340",
            "merchants_affected": 12,
            "sla_breach":         "QuickMart",
        },
        "recovery": {
            "rows_loaded":       824,
            "quarantined_count": 23,
        },
        "rollback": {
            "status": "SUCCESS"
        },
        "hardening": {
            "alarms_created": [
                {"alert_name": "sigma-eventhub-lag-spike"}
            ]
        },
        "agent_performance": [
            {"agent": "Forensics", "duration_sec": 4},
            {"agent": "Recovery",  "duration_sec": 8},
        ],
    }

    result = write_report(sample_findings)

    print(json.dumps(result, indent=2))
